version: '3.7'

services:
  web:
    build: .
    command: uvicorn main.api.main:app --reload
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
